[[redirects]]
from = "https://dxmg.io/*"
to = "https://dxmg.de/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.dxmg.io/*"
to = "https://dxmg.de/:splat"
status = 301
force = true

[[redirects]]
from = "https://david-matusiewicz.com/*"
to = "https://dxmg.de/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.david-matusiewicz.com/*"
to = "https://dxmg.de/:splat"
status = 301
force = true

[[redirects]]
from = "/*"
to = "/404.html"
status = 404

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [ ".cache" ]
