[[redirects]]
from = "/slides/"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "https://dxmg.io/*"
to = "https://dxmg.de/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.dxmg.io/*"
to = "https://dxmg.de/:splat"
status = 301
force = true
